clinical-ingestion/helm-charts/deid/.helmignore
clinical-ingestion/helm-charts/deid/Chart.yaml
clinical-ingestion/helm-charts/deid/README.md
clinical-ingestion/helm-charts/deid/templates/NOTES.txt
clinical-ingestion/helm-charts/deid/templates/_helpers.tpl
clinical-ingestion/helm-charts/deid/templates/deployment.yaml
clinical-ingestion/helm-charts/deid/templates/service.yaml
clinical-ingestion/helm-charts/deid/templates/tests/test-connection.yaml
clinical-ingestion/helm-charts/deid/values.yaml

This PR adds a new Chart project to deploy an instance of the De-ID
service to a K8S cluster.
The chart deploys the container image created by @ibmatc to run the
de-id service JAR as described in the Alvearie de-id github page.

De-Identification chart and integration

---

clinical-ingestion/helm-charts/alvearie-ingestion/values.yaml

This commit exposes a second port on the nifi LB service that accepts
FHIR bundles over HTTP.

Expose port 7001 for HTTP processor that accepts FHIR bundles

---

clinical-ingestion/helm-charts/alvearie-ingestion/de-id-pattern-values.yaml
clinical-ingestion/helm-charts/alvearie-ingestion/templates/NOTES.txt
clinical-ingestion/helm-charts/alvearie-ingestion/values.yaml
clinical-ingestion/helm-charts/deid/templates/NOTES.txt
clinical-ingestion/helm-charts/fhir/templates/NOTES.txt
clinical-ingestion/helm-charts/fhir/values.yaml
clinical-ingestion/helm-charts/nifi-registry/templates/NOTES.txt

This commit includes creating or updating the corresponding NOTES.txt
files for all the charts we have created thus far.
The NOTES.txt file are meant to be a quick introduction to a chart
deployer about how to access the chart's service(s).
This is what users will see when they deploy the `alvearie-ingestion` chart (the pattern name and list of services will vary based on the pattern they deploy).
```
Welcome to the
d8888 888                                    d8b
d88888 888                                    Y8P
d88P888 888
d88P 888 888 888  888  .d88b.   8888b.  888d888 888  .d88b.
d88P  888 888 888  888 d8P  Y8b     "88b 888P"   888 d8P  Y8b
d88P   888 888 Y88  88P 88888888 .d888888 888     888 88888888
d8888888888 888  Y8bd8P  Y8b.     888  888 888     888 Y8b.
d88P     888 888   Y88P …
```

Update notes to the various charts we have created so far

---

clinical-ingestion/helm-charts/alvearie-ingestion/values.yaml
clinical-ingestion/helm-charts/deid/values.yaml
clinical-ingestion/helm-charts/fhir/values.yaml

This commit changes the location of the various container images that we
use in alvarie's ingestion pattern from our personal docker hub accounts
to the official alvearie account.
I have uploaded the images to docker hub under the new account here:
- https://hub.docker.com/repository/docker/alvearie/nars
- https://hub.docker.com/repository/docker/alvearie/fhir-proxy
- https://hub.docker.com/repository/docker/alvearie/deid

Update the images from our personal docker hub accounts to alvearie's

---

clinical-ingestion/helm-charts/alvearie-ingestion/values.yaml

The first two changes in this PR are not significant.  They are for whitespace (detected by my editor).  The important change is switching to use the configure script that is now stored on Alvearie.  Originally, while in dev, the script was pushed up to a temporary location on the integration squad github to allow experimenting with the process.  This was fine at the time but I believe there is a possible/probable problem due to the access token expiring.  In addition, it just makes sense that we would use the version on Alvearie to keep it all together.

fix script location to be alvearie

---

clinical-ingestion/helm-charts/alvearie-ingestion/Chart.yaml
clinical-ingestion/helm-charts/alvearie-ingestion/charts/deid/values.yaml

The "latest" tag is not applied to the current container build out in the alvearie docker repo. Switched to 0.0.1 to reflect the current/only version.  Probably preferable to "latest" anyway so we don't get unexpected changes to behavior.

Fix deid deployment version

---

.github/workflows/test-charts.yaml
clinical-ingestion/helm-charts/alvearie-ingestion/Chart.yaml
clinical-ingestion/helm-charts/alvearie-ingestion/charts/fhir/values.yaml
clinical-ingestion/helm-charts/alvearie-ingestion/ci/chart-testing-values.yaml
clinical-ingestion/helm-charts/alvearie-ingestion/values.yaml

This commit enhances the existing charts CI pipeline to include
installing the chart in addition to just linting the charts.
The installation is done in a `kind` kubernetes cluster that is setup as
part of the Github Action.
A new `*-values.yaml` file is added that has the configuration necessary
to install the chart for testing purposes. That includes disabling
certain components that are not supported by the `kind` cluster such as
the prometheus stack and using `LoadBalancer` services.
This test values.yaml also includes installing the de-id service and the
FHIR Proxy for better coverage.
Also, provide a specific FHIR Proxy container image version.

Implement CI Chart install

---

clinical-ingestion/helm-charts/alvearie-ingestion/Chart.yaml
clinical-ingestion/helm-charts/alvearie-ingestion/ci/chart-testing-values.yaml
clinical-ingestion/helm-charts/alvearie-ingestion/values.yaml

Change the values.yaml back to what it was before the chart install
phase was added. Those values should be in the
`chart-testing-values.yaml` but are not part of the default
`values.yaml`

Revert intermediate test changes to values.yaml

---

clinical-ingestion/helm-charts/alvearie-ingestion/Chart.yaml
clinical-ingestion/helm-charts/alvearie-ingestion/README.md
clinical-ingestion/helm-charts/alvearie-ingestion/values.yaml

After our investigation we have decided to disable the monitoring solution by default and allow users to enable it if they wish.  This PR sets the proper enabled flags to false and provides documentation as to the necessary changes that need to be made to enable in the future.

Disablemonitoring

---

clinical-ingestion/helm-charts/alvearie-ingestion/Chart.yaml
clinical-ingestion/helm-charts/alvearie-ingestion/charts/cohort-service/Chart.yaml
clinical-ingestion/helm-charts/alvearie-ingestion/charts/cohort-service/templates/NOTES.txt
clinical-ingestion/helm-charts/alvearie-ingestion/charts/cohort-service/templates/_helpers.tpl
clinical-ingestion/helm-charts/alvearie-ingestion/charts/cohort-service/templates/deployment.yaml
clinical-ingestion/helm-charts/alvearie-ingestion/charts/cohort-service/templates/service.yaml
clinical-ingestion/helm-charts/alvearie-ingestion/charts/cohort-service/values.yaml
clinical-ingestion/helm-charts/alvearie-ingestion/ci/chart-testing-values.yaml
clinical-ingestion/helm-charts/alvearie-ingestion/templates/NOTES.txt
clinical-ingestion/helm-charts/alvearie-ingestion/values.yaml

This commit adds the Cohort Service's chart as a sub-chart of the
Clinical Ingestion main chart. This allows users to try out the cohort
service if needed. By default the service is disabled.
This commit also enabled the `LoadBalancer` for the FHIR service by
default per a discussion in slack about why we had turned it to
`ClusterIP`, which may have been accidentally.
Since we added a new service I bumped the chart version a whole point :)
After this commit the ingestion framework may include the cohort service
as shown below:
```
Welcome to the
d8888 888                                    d8b
d88888 888                                    Y8P
d88P888 888
d88P 888 888 888  888  .d88b.   8888b.  888d888 888  .d88b.
d88P  888 888 888  888 d8P  Y8b     "88b 888P"   888 d8P  Y8b
d88P   888 888 …
```

Add Cohort Service sub-chart to Clinical Ingestion Chart

---

nifi-processors/nifi-health-patterns-bundle/nifi-health-patterns-processors/src/main/java/com/ibm/healthpatterns/processors/common/FHIRServiceCustomProcessor.java
nifi-processors/nifi-health-patterns-bundle/nifi-health-patterns-processors/src/main/java/com/ibm/healthpatterns/processors/deid/DeIdentifyAndPostToFHIR.java
nifi-processors/nifi-health-patterns-bundle/nifi-health-patterns-processors/src/main/java/com/ibm/healthpatterns/processors/terminology/FHIRConceptMapTranslate.java
nifi-processors/nifi-health-patterns-bundle/nifi-health-patterns-processors/src/test/java/com/ibm/healthpatterns/processors/common/FHIRCustomProcessorTest.java
nifi-processors/nifi-health-patterns-bundle/nifi-health-patterns-processors/src/test/java/com/ibm/healthpatterns/processors/deid/DeIdentifyAndPostToFHIRTest.java
nifi-processors/nifi-health-patterns-bundle/nifi-health-patterns-processors/src/test/java/com/ibm/healthpatterns/processors/terminology/FHIRConceptMapTranslateTest.java
services/common/.gitignore
services/common/LICENSE
services/common/README.md
services/common/pom.xml
services/common/src/main/java/com/ibm/healthpatterns/core/FHIRService.java
services/common/src/main/java/com/ibm/healthpatterns/core/FHIRServiceException.java
services/common/src/test/java/com/ibm/healthpatterns/core/FHIRServiceTest.java
services/deid-core/pom.xml
services/deid-core/src/main/java/com/ibm/healthpatterns/deid/DeIdentifier.java
services/deid-core/src/test/java/com/ibm/healthpatterns/deid/DeIdentifierTest.java
services/pom.xml
services/terminology-service-core/src/main/java/com/ibm/healthpatterns/terminology/TerminologyService.java
services/terminology-service-core/src/test/java/com/ibm/healthpatterns/terminology/TerminologyServiceTest.java

The de-id and terminology service use cases both require communication
to the FHIR Server and they had several similarities in terms of both
their implementation and testing.
This commit implements a refactoring extracting the common code into a
new couple of classes FHIRService and FHIRServieTest, that live in a new
project called common.
Refactoring the tests of the custom processors to extract commonalities
is also included in this commit.
The corresponding necessary build changes to build and get the right
visibility on the child projects are included too.
This is what the reactor currently looks like after this commit:
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Alvearie Health Patterns - Core Services 0.0.1-SNAPSHOT: …
```

Refactor Common Component with base FHIR Service

---

.github/workflows/ibm.yaml
README.md

This PR includes a custom Github Action that deploys the main Alvearie Ingestion Helm Chart, with all of its services enabled, to the
IBM Cloud in order to validate that the code being submitted is correct and won't break the Chart installation.

Deploy Chart to IBM Cloud

---

clinical-ingestion/helm-charts/alvearie-ingestion/Chart.yaml
clinical-ingestion/helm-charts/alvearie-ingestion/templates/NOTES.txt
clinical-ingestion/helm-charts/alvearie-ingestion/templates/ingress-nifi-http-post.yaml

I missed renaming a few places that still referred to the nifi input port as 'REST' - so fixing it to call it the Nifi HTTP Post API.  Not perfect, but better.

Atc rename nifi api

---

nifi-processors/nifi-health-patterns-bundle/nifi-health-patterns-processors/src/main/java/com/ibm/healthpatterns/processors/hl7tofhir/HL7ToFhirProcessor.java
nifi-processors/nifi-health-patterns-bundle/nifi-health-patterns-processors/src/test/java/com/ibm/healthpatterns/processors/hl7tofhir/Hl7ToFhirProcessorTest.java

Updated processor to use input/output callbacks, and added tests to validate non-success paths.

Resolved: Update HL7toFhirProcessor to use Callbacks

---

services/expose-kafka/exposekafka.py

Increases the default request size limit for kafka producer within the expose-kafka service.

fix request size limit on kafka producer

---

cohort-service/pom.xml
cohort-service/src/main/java/com/ibm/healthpatterns/app/CohortService.java

I updated the POM to pin versions of upstream info.cqframework JARs in order to avoid version mismatches in the runtime classpath. I also applied a small fix to the updateLibrary method of the CohortService so that it refreshes the CQL directory on update.

Bug fixes for cohort-engine 1.0.1 pre-release updates

---

cohort-service/pom.xml
cohort-service/src/main/java/com/ibm/healthpatterns/app/CohortService.java

There are two types of callbacks available to clients using the
CQLEvaluator. One is a legacy callback that only exposes expression
complete events and the other is a newer API that exposes context
begin/end events in addition to expresion complete events. The
CohortService code was using an API that accepts the legacy callback,
but passing a modern callback. CqlEvaluator will wrap a legacy callback
in a modern callback proxy and noop the context begin/end events in
those cases. CohortService needs the context begin/end events, so I
updated the code to use the the correct API call for an
EvaluationResultCallback.

Fix callback usage

---

clinical-ingestion/README.md
docs/index.md
docs/roadmap.md

This directory/readme is no longer used.

clean up the clinical-ingestion directory after readme updates

---

clinical-enrichment/tests/tests/run-fvttests.sh
clinical-enrichment/tests/tests/run-ivttests.sh
clinical-enrichment/tests/tests/run-smoketests.sh
clinical-enrichment/tests/tests/toolchain-envsetup.sh

Refactor the enrich test scripts execute the common setup steps in a separate script (toolchain-envsetup.sh).
Add logic to execute enrich tests or ingest tests based on the cluster namespace (clinicial-enrich OR clinical-ingestion)

Add ingest tests to health-patterns repo toolchain

---

.github/workflows/ibm.yaml

Use github.run_id in place of github.actor for more unique namespace names.  
Added CLUSTER_ID, CIS_INSTANCE, and POOL_ID to the environment and replaced hard-coded values in the commands.

Use run_id for unique namespace

---

test-umbrella/tests/tests/run-fvttests.sh
test-umbrella/tests/tests/run-ivttests.sh
test-umbrella/tests/tests/run-smoketests.sh

Add the ENV_CLEAN_UP flag as input to the toolchain run.  Default value is true, and it can be changed to false on a manual start of the toolchains to keep the deployments/namespaces for debug.

Add Clean Up Flag To Toolchain

---

enrich/pom.xml
enrich/src/test/resources/enrich-flow.properties
ingest/pom.xml
ingest/src/test/resources/clinical-ingestion-flow.properties
test-umbrella/tests/tests/run-fvttests.sh
test-umbrella/tests/tests/run-ivttests.sh
test-umbrella/tests/tests/run-smoketests.sh
test-umbrella/tests/tests/toolchain-envsetup.sh

Removing input the port parameter from each of the service URLs since it is not used.

Remove unused port parameter as input to testcase builds

---

enrich/README.md
helm-charts/health-patterns/README_Helm.md
helm-charts/health-patterns/templates/nifi-cluster.yaml
helm-charts/health-patterns/values.yaml
ingest/README.md

Update the documentation to describe how to deploy nifi via Nifikop as the "default" option.  Move the insecure (obsolete) approach to a backup option (not recommended).

Atc default to nifikop

---

data-access/docker-compose.yaml
data-access/pom.xml
services/ibm-fhir-server/data-access/README.md

bump ibm-fhir-server from 4.11.0 to 4.11.1
