clinical-ingestion/Clinical_Flow_Reference_Design.json, clinical-ingestion/README.md, nifi-components/FHIR_Terminology_Mapping.json, nifi-components/README.md, nifi-components/Send_to_FHIR_and_Post_Errors.json
Changes to be committed:
new file:   clinical-ingestion/Clinical_Flow_Reference_Design.json
new file:   clinical-ingestion/README.md
new file:   nifi-components/FHIR_Terminology_Mapping.json
new file:   nifi-components/README.md
new file:   nifi-components/Send_to_FHIR_and_Post_Errors.json
Delivering first pass at Clinical Ingestion Flow NiFi pipeline, with corresponding components.
Signed-off-by: Adam T. Clark<atclark@us.ibm.com>
=> Initial delivery of Clinical Ingestion Flow

clinical-ingestion/utilities/setupFlow.py
This is current (cleaned/consolidated) version of the python script that we are running to help set up the clinical ingestion flow.  It prints alot of information as it runs to help with debugging when needed.  Relies on the nifi-api
Loads the flow
Sets specific passwords
Enables all controllers that are disabled
=> new helper script for clinical ingestion setup

clinical-ingestion/helm-charts/nifi-registry/config/providers.xml, clinical-ingestion/helm-charts/nifi-registry/values.yaml
Add the ability to control the branch/username/password used to connect
to github.  Provide defaults in values.yaml.
=> Enhance Nifi registry configurability

clinical-ingestion/helm-charts/README.md
Update the alvearie-ingestion chart READMME.md.
=> Small documentation update after chart restructuring

clinical-ingestion/helm-charts/README.md
Add some instructions on how to run the chart linting github action locally.
=> Add local linting instructions

clinical-ingestion/utilities/setupClinicalIngestionFlow.py
Update script to make it consistent with the new flow
=> fix password ids to make consistent with new flow

.github/workflows/test-charts.yaml, clinical-ingestion/helm-charts/README.md
Fix some broken links in `helm-charts/README.md`
=> Fix broken links

clinical-ingestion/utilities/setupClinicalIngestionFlow.py
This change allows you to add an extra (3rd) argument for the registry.  Something like
./setupClinicalIngestionFlow.py http://a6dcadb6-us-south.lb.appdomain.cloud:8080 integrati0n Prod
Leaving it off will use the "default" registry.  
Note, for extra credit, you can add a 4th argument for the bucket name if you like (default bucket is still Health_Patterns)
./setupClinicalIngestionFlow.py http://a6dcadb6-us-south.lb.appdomain.cloud:8080 integrati0n Prod someotherbucket
=> Adding an additional argument for the registry

nifi-processors/nifi-health-patterns-bundle/nifi-health-patterns-processors/src/main/java/com/ibm/healthpatterns/processors/acdprocessors/ACDProcessor.java, nifi-processors/nifi-health-patterns-bundle/nifi-health-patterns-processors/src/main/java/com/ibm/healthpatterns/processors/mimic/GenerateFHIRFromMimic.java
This commit adds better tags to some of the existing NiFI Custom
Processors.
=> Update Custom Processor Tags

clinical-ingestion/utilities/README.md, clinical-ingestion/utilities/setupClinicalIngestionFlow.py
Tweak to allow user to provide explicit version number.
=> Addversion

clinical-ingestion/helm-charts/alvearie-ingestion/Chart.yaml, clinical-ingestion/helm-charts/alvearie-ingestion/values.yaml, clinical-ingestion/utilities/setupClinicalIngestionFlow.py
This change adds the automatic start for the new clinical ingestion processor group that was previously added by the script.
=> Add auto starting for new processor group

clinical-ingestion/helm-charts/alvearie-ingestion/Chart.yaml, clinical-ingestion/helm-charts/alvearie-ingestion/README.md, clinical-ingestion/helm-charts/alvearie-ingestion/README_INGRESS.md, clinical-ingestion/helm-charts/alvearie-ingestion/aws-ingress-enabled-values.yaml, clinical-ingestion/helm-charts/alvearie-ingestion/azure-ingress-enabled-values.yaml, clinical-ingestion/helm-charts/alvearie-ingestion/ibm-ingress-enabled-values.yaml, clinical-ingestion/helm-charts/alvearie-ingestion/templates/ingress-cohort.yaml, clinical-ingestion/helm-charts/alvearie-ingestion/templates/ingress-deid.yaml, clinical-ingestion/helm-charts/alvearie-ingestion/templates/ingress-fhir-deid.yaml, clinical-ingestion/helm-charts/alvearie-ingestion/templates/ingress-fhir.yaml, clinical-ingestion/helm-charts/alvearie-ingestion/templates/ingress-grafana.yaml, clinical-ingestion/helm-charts/alvearie-ingestion/templates/ingress-kafka.yaml, clinical-ingestion/helm-charts/alvearie-ingestion/templates/ingress-nifi-http-post.yaml, clinical-ingestion/helm-charts/alvearie-ingestion/templates/ingress-nifi-registry.yaml, clinical-ingestion/helm-charts/alvearie-ingestion/templates/ingress-nifi.yaml
This includes instructions for deploying Clinical Ingestion to Azure and AWS using Ingress.
=> Atc azure ingress

.github/workflows/ibm.yaml
Also, remove the unused PORT variable.
=> Update IBM Cloud install action to always uninstall

clinical-ingestion/helm-charts/alvearie-ingestion/Chart.yaml, clinical-ingestion/helm-charts/alvearie-ingestion/templates/NOTES.txt
The NOTES.txt file had incorrect notes for the kafka service. This updates the notes to generate the correct information
=> Fix Kafka Notes

clinical-ingestion/utilities/setupClinicalIngestionFlow.py
This PR updates the setup script to set passwords in the new cms parameter context from M/M.  The script has already been included in a new docker image for the utility scripts  alvearie/nifi-setup:0.0.3
=> update password change for new context

data-access/README.md, data-access/docker-compose.yaml
=> update data-access README to use the newly available alvearie keycloak images

clinical-ingestion/helm-charts/alvearie-ingestion/Chart.yaml, clinical-ingestion/helm-charts/alvearie-ingestion/templates/ingress-fhir-proxy.yaml
=> Switch . to -

data-access/README.md, data-access/docker-compose.yaml, data-access/fhir/configDropins/overrides/keycloakJwt.xml
=> rename and tweak the liberty configDropin for working with keycloak JWTs

clinical-ingestion/helm-charts/alvearie-ingestion/Chart.yaml, clinical-ingestion/helm-charts/alvearie-ingestion/templates/NOTES.txt
Fixes the deployment output for new cluster
=> use https now

clinical-ingestion/helm-charts/alvearie-ingestion/Chart.yaml, clinical-ingestion/helm-charts/alvearie-ingestion/values.yaml, clinical-ingestion/utilities/README.md, clinical-ingestion/utilities/setupClinicalIngestionFlow.py
Script update to place enrichment flow on nifi canvas.  Also added better optional argument support for developers who want to load custom registries/buckets/versions instead of the default/latest. Note: nifi-setup:0.0.4 has already been built and pushed to dockerhub
=> update to load enrichment flow

cohort-service/pom.xml, cohort-service/src/main/java/com/ibm/healthpatterns/app/CQLExecutionCallback.java, cohort-service/src/main/java/com/ibm/healthpatterns/app/CohortService.java, cohort-service/src/test/java/com/ibm/healthpatterns/app/CohortServiceAppTest.java, cohort-service/src/test/resources/FemalePatients-1.0.0.cql, cohort-service/src/test/resources/MaleorFemalePatients-1.0.0.cql
Updates to cohort health-pattern example to align with latest changes made to underlying R1 version of cohort service, including:
- Change in cohort engine wrapper classname - CqlEvaluator
- pom file updates
- A couple additional JUnit test cases
=> Cohort r1 updates

cohort-service/chart/templates/ingress.yaml, helm-charts/health-patterns/clinical_enrichment.yaml, helm-charts/health-patterns/clinical_ingestion.yaml, helm-charts/health-patterns/values.yaml, utilities/loadHealthPatternsFlows.py
A couple of small fixes I missed in the last commit
Fixes #149.
=> Fix helm config for new charts

helm-charts/health-patterns/values.yaml
=> Force deid container tag to 0.0.1

helm-charts/health-patterns/values.yaml, services/expose-kafka/Dockerfile, services/expose-kafka/README.md, services/expose-kafka/exposekafka.py
New branch and PR for just the expose-kafka service.
=> new branch and pr for expose kafka

helm-charts/health-patterns/templates/ingress-nifi-http-post.yaml
=> Update service name to hard-code "alvearie"

services/fhir-trigger/Dockerfile, services/fhir-trigger/README.md, services/fhir-trigger/fhirtrigger.py
Sending the deployment yml separately (not as part of a git delivery).
=> initial commit for fhir-trigger service

data-access/docker-compose.yaml, data-access/fhir/config/default/fhir-server-config.json, data-access/pom.xml
Also added parameter disambiguation to avoid warnings when us core or similar IGs are packaged.
=> Lock in to IBM FHIR Server 4.8.3 and Keycloak extensions 0.2.0

helm-charts/health-patterns/templates/NOTES.txt
=> Fix typo in Notes.txt

clinical-enrichment/test/src/main/java/tests/Enrich_Flow.java, clinical-enrichment/test/src/main/resources/configs/simpleDEID.json, clinical-enrichment/test/src/main/resources/configs/simpleDEIDUpdate.json, clinical-enrichment/test/src/main/resources/scenarios/deid_FHIR_Patient_DELETE.json, clinical-enrichment/test/src/main/resources/scenarios/enrich_DEID_Prep_Config_CRUD.json, clinical-enrichment/test/src/main/resources/scenarios/enrich_DEID_Prep_No_Store_Patient.json, clinical-enrichment/test/src/main/resources/scenarios/enrich_DEID_Prep_Store_Patient.json, clinical-enrichment/test/src/main/resources/scenarios/pri_FHIR_Patient_DELETE.json
New DEID Prep Serivce Configuration Tests
Changes to existing test to support path-based ingress
=> Changes to support path-based ingress and DEID Config Tests

cohort/README.md, enrich/README.md, helm-charts/health-patterns/values.yaml, ingest/README.md
Add default to readme for ingress classname
=> fix class name default

.github/workflows/ibm.yaml, clinical-enrichment/pom.xml, clinical-enrichment/src/test/java/categories/EnrichmentInit.java, clinical-enrichment/src/test/java/categories/EnrichmentInitTests.java, clinical-enrichment/src/test/java/tests/Enrich_Flow.java, clinical-enrichment/src/test/resources/enrich-flow.properties, clinical-enrichment/src/test/resources/scenarios/enrich_NLP_Insights.json, clinical-enrichment/src/test/resources/scenarios/enrich_NLP_Insights_Config_CRUD.json, clinical-enrichment/src/test/resources/scenarios/enrich_NLP_Insights_Config_Errors.json, clinical-enrichment/src/test/resources/scenarios/enrich_NLP_Insights_Deploy_Default.json, clinical-enrichment/src/test/resources/scenarios/enrich_NLP_Insights_healthCheck.json, clinical-enrichment/tests/tests/run-fvttests.sh, clinical-enrichment/tests/tests/run-ivttests.sh, clinical-enrichment/tests/tests/run-smoketests.sh
Added an EnrichmentInit category for health check tests and any initial deployment verification tests..
Added the NLP-Insights configuration Create-Read-Update-Delete (CRUD) tests.
=> Rdg nlp insights

.github/workflows/ibm.yaml
Add execution of the new EnrichmentInit category to execute the healthCheck and Default Deploy tests that were added.
=> Add EnrichmentInit Tests

services/nlp-insights/text_analytics/app.py
=> fix invalid configs

clinical-enrichment/src/test/resources/scenarios/enrich_NLP_Insights_Config_CRUD.json, clinical-enrichment/src/test/resources/scenarios/enrich_NLP_Insights_Config_Errors.json
=> Fixed NLP Insights tests that worked around now fixed issues

services/nlp-insights/text_analytics/app.py
=> fix missing nlp service object

clinical-enrichment/tests/tests/run-fvttests.sh, clinical-enrichment/tests/tests/run-ivttests.sh, clinical-enrichment/tests/tests/run-smoketests.sh
=> Hide the ACD API Key

.github/workflows/ibm.yaml
Move the ACP API Key into a github secret
=> Create ACD_API_KEY secret

clinical-enrichment/src/test/java/categories/NLPEnrichment.java, clinical-enrichment/src/test/java/categories/NLPEnrichmentTests.java, clinical-enrichment/src/test/java/tests/Enrich_Flow.java, clinical-enrichment/tests/tests/run-ivttests.sh
=> Temp removal of NLP Tests

enrich/README.md, services/nlp-insights/README.md
=> update some readmes

services/nlp-insights/text_analytics/app.py
=> fix missing config name

clinical-enrichment/src/test/java/categories/NLPEnrichmentFVT.java, clinical-enrichment/src/test/java/categories/NLPEnrichmentFVTTests.java, clinical-enrichment/src/test/java/tests/Enrich_Flow.java, clinical-enrichment/src/test/resources/configs/NLP-IVT-values.yaml, clinical-enrichment/src/test/resources/configs/NLP-POST-config.json, clinical-enrichment/src/test/resources/configs/NLP-POST-invalid-config.json, clinical-enrichment/src/test/resources/configs/NLP-PUT-config.json, clinical-enrichment/src/test/resources/configs/NLP-PUT-invalid-config.json, clinical-enrichment/src/test/resources/scenarios/enrich_NLP_Insights_Config_CRUD.json, clinical-enrichment/src/test/resources/scenarios/enrich_NLP_Insights_Config_Errors.json, clinical-enrichment/src/test/resources/scenarios/enrich_NLP_Insights_Config_Use.json, clinical-enrichment/tests/tests/run-fvttests.sh, clinical-enrichment/tests/tests/run-ivttests.sh, clinical-enrichment/tests/tests/toolchain-envsetup.sh, ingest/src/test/resources/configs/NLP-ingestion-values.yaml
Let me know if you'd like a guided tour/review
=> Changes for existing NLP-Insights tests to match the new & improved function

services/nlp-insights/text_analytics/app.py
=> hide config data

clinical-enrichment/src/test/java/tests/Enrich_Flow.java, clinical-enrichment/src/test/resources/scenarios/enrich_NLP_Insights_Override_CRUD.json, clinical-enrichment/src/test/resources/scenarios/enrich_NLP_Insights_Override_Use.json
Let me know if you want a review meeting for this.....    Thanks
=> Add NLP-Insights Override Tests

.github/workflows/ibm.yaml, clinical-enrichment/tests/tests/run-ivttests.sh, ingest/pom.xml, ingest/src/test/java/tests/Ingestion_Flow.java, ingest/src/test/resources/clinical-ingestion-flow.properties, ingest/src/test/resources/configs/NLP-ingestion-values.yaml, ingest/src/test/resources/scenarios/ingest_FHIR_NLP_Insights_Override.json
Let me know if you'd like an explanation of this via webex.
=> Add NLP Override testing on a bundle to the ingestion flow

clinical-enrichment/tests/tests/run-ivttests.sh, ingest/src/test/resources/scenarios/ingest_FHIR_NLP_Insights_Override.json
=> Removed ACD config create from test & added ACD Api key for deploy

enrich/README.md, helm-charts/health-patterns/clinical_enrichment.yaml, helm-charts/health-patterns/clinical_ingestion.yaml, ingest/README.md, utilities/initialize-nifi.sh, utilities/startHealthPatternsFlow.py
=> update deployment scripts to handle nlp insights

services/ibm-fhir-server/README.md, services/ibm-fhir-server/data-access/Dockerfile, services/ibm-fhir-server/data-access/README.md, services/ibm-fhir-server/data-access/pom.xml
=> introduce a data-access fhir server dockerfile

helm-charts/health-patterns/Chart.yaml, helm-charts/health-patterns/README_Helm.md, helm-charts/health-patterns/nifikop.yaml, helm-charts/health-patterns/templates/NOTES.txt, helm-charts/health-patterns/templates/ingress-nifi.yaml, helm-charts/health-patterns/templates/ingress-nifi2.yaml, helm-charts/health-patterns/templates/ingress-nifi_new.yaml, helm-charts/health-patterns/templates/nifi-cluster.yaml, helm-charts/health-patterns/templates/nifi-data-flow.yaml, helm-charts/health-patterns/templates/nifi-enrich-parameter-secret.yaml, helm-charts/health-patterns/templates/nifi-enrichment-parameter-context.yaml, helm-charts/health-patterns/templates/nifi-ingestion-parameter-context.yaml, helm-charts/health-patterns/templates/nifi-ingestion-parameter-secret.yaml, helm-charts/health-patterns/templates/nifi-registry-client.yaml, helm-charts/health-patterns/values.yaml, utilities/initialize-nifi.sh
=> Use NifiKop to deploy secure Nifi

helm-charts/health-patterns/README_Helm.md, helm-charts/health-patterns/templates/nifi-data-flow.yaml, helm-charts/health-patterns/templates/nifi-ingestion-parameter-context.yaml
=> Fix a few issues found in secured Nifi

helm-charts/health-patterns/templates/nifi-enrichment-parameter-context.yaml
=> Fix deid config name in Nifikop deploy

helm-charts/health-patterns/templates/nifi-enrichment-parameter-context.yaml
=> Replace placeholders with actual values

.github/workflows/ibm.yaml
Append the "github.actor" property to the namespace name for unique namespace names so that different github users can create PRs at the same time and not interfere with each other.
=> Unique Namespace based on User

test-umbrella/tests/tests/run-fvttests.sh, test-umbrella/tests/tests/run-ivttests.sh
=> Reduced wait times for secure Nifi Deploy and delete

test-umbrella/tests/tests/run-fvttests.sh, test-umbrella/tests/tests/run-ivttests.sh
The secure Nifi deployment is now coming up just as fast as the unsecure Nifi deployment so I removed the extra wait times.
=> Remove extra wait times for secure Nifi coming up

helm-charts/health-patterns/README_Helm.md, helm-charts/health-patterns/README_minikube.md, helm-charts/health-patterns/values.yaml
=> Document how to use miniube to deploy Health Patterns

helm-charts/health-patterns/templates/nifi-data-flow.yaml
=> Upgrade runOnce to syncMode in dataflow.yaml

docs/charts/index.yaml, helm-charts/health-patterns/values.yaml
=> Bump dataflow versions for nifikop

helm-charts/health-patterns/values.yaml
=> Update to Nifi flow

helm-charts/health-patterns/values.yaml
=> upgrade flow version

ingest/pom.xml, ingest/src/test/resources/clinical-ingestion-flow.properties, test-umbrella/tests/tests/run-fvttests.sh, test-umbrella/tests/tests/run-ivttests.sh, test-umbrella/tests/tests/run-smoketests.sh
=> Support different kafka input topic names based on deployment

helm-charts/health-patterns/README_Helm.md
=> Update readme for secure nifi

test-umbrella/tests/tests/NifiKopValues.sh, test-umbrella/tests/tests/README.md, test-umbrella/tests/tests/run-fvttests.sh, test-umbrella/tests/tests/run-ivttests.sh, test-umbrella/tests/tests/run-smoketests.sh, test-umbrella/tests/tests/toolchain-envsetup.sh
Add INGRESS_SUBDOMAIN, DEPLOY_WAIT, and HELM_TIMEOUT to Toolchain Environment Variables.
Add date/time stamps in order to determine actual helm install, if needed.
Add README to the umbrella/tests/tests folder to document the toolchain scripts/
=> Rdg toolchain env

services/expose-kafka/exposekafka.py
=> Format Expose-Kafka's response message properly for JSON data

.github/workflows/ibm.yaml
Sorry for another review.  I forgot to include this github action change in the previous pull request to remove the port parameter.
=> Remove PORT parameter from maven build cmd

services/ibm-fhir-server/fhir-cql-eval/Dockerfile, services/ibm-fhir-server/fhir-cql-eval/README.md, services/ibm-fhir-server/fhir-cql-eval/pom.xml
=> add new fhir pattern for cql eval

.github/workflows/health-patterns-build-action.yml
=> automate the fhir-trigger service build

ingest/src/test/java/categories/FHIRDataQualityBLK.java, ingest/src/test/java/categories/FHIRDataQualityBLKTests.java, ingest/src/test/java/tests/Ingestion_Flow.java, ingest/src/test/resources/scenarios/ingest_FHIR.json, ingest/src/test/resources/scenarios/ingest_FHIR_DEID.json, ingest/src/test/resources/scenarios/ingest_FHIR_DEID_TERM.json, ingest/src/test/resources/scenarios/ingest_FHIR_DEID_TERM_BLK.json, ingest/src/test/resources/scenarios/ingest_FHIR_Data_Quality_BLK.json, ingest/src/test/resources/scenarios/ingest_FHIR_Errors.json, ingest/src/test/resources/scenarios/ingest_FHIR_Errors_BLK.json, ingest/src/test/resources/scenarios/ingest_FHIR_NLP_Insights.json, ingest/src/test/resources/scenarios/ingest_FHIR_NLP_Insights_BLK.json, ingest/src/test/resources/scenarios/ingest_FHIR_NLP_Insights_Override.json, ingest/src/test/resources/scenarios/ingest_FHIR_NLP_Insights_Override_BLK.json, ingest/src/test/resources/scenarios/ingest_FHIR_No_ASCVD.json, ingest/src/test/resources/scenarios/ingest_FHIR_No_ASCVD_BLK.json, ingest/src/test/resources/scenarios/ingest_FHIR_TERM.json, ingest/src/test/resources/scenarios/ingest_FHIR_TERM_BLK.json, test-umbrella/tests/tests/run-ivttests.sh
Add a basic test of the fhir-data-quality service to IVT.
=> FHIR Data Quality Tests

services/ibm-fhir-server/fhir-cql-eval/examples/CQLDemoNotebook.ipynb, services/ibm-fhir-server/fhir-cql-eval/examples/README.md
=> adding example cql notebook

services/ibm-fhir-server/fhir-cql-eval/README.md
=> readme update for cql config

helm-charts/health-patterns/Chart.yaml
=> wrong version on trigger chart

helm-charts/health-patterns/Chart.yaml, helm-charts/health-patterns/clinical_enrichment.yaml, helm-charts/health-patterns/clinical_ingestion.yaml, helm-charts/health-patterns/values.yaml, utilities/initialize-nifi.sh, utilities/startHealthPatternsFlow.py
=> Revert to plain Nifi

helm-charts/health-patterns/Chart.yaml, test-umbrella/tests/tests/NifiKopValues.sh, test-umbrella/tests/tests/run-fvttests.sh, test-umbrella/tests/tests/run-ivttests.sh, test-umbrella/tests/tests/run-smoketests.sh, test-umbrella/tests/tests/testCleanUp.sh, test-umbrella/tests/tests/toolchain-envsetup.sh
Add environment variable DEPLOY_NIFIKOP to control deployment of nifikop and related pipeline configuration in the toolchain tests.
=> Add environment variable DEPLOY_NIFIKOP

enrich/README.md, ingest/README.md
=> update to latest helm configs

enrich/src/test/resources/scenarios/enrich_NLP_Insights_Config_CRUD.json, enrich/src/test/resources/scenarios/enrich_NLP_Insights_Config_Errors.json, enrich/src/test/resources/scenarios/enrich_NLP_Insights_Config_Use.json, enrich/src/test/resources/scenarios/enrich_NLP_Insights_Override_CRUD.json, enrich/src/test/resources/scenarios/enrich_NLP_Insights_Override_Use.json, ingest/src/test/resources/scenarios/ingest_FHIR_NLP_Insights_Override.json, ingest/src/test/resources/scenarios/ingest_FHIR_NLP_Insights_Override_BLK.json
=> nlp-insights response changes

enrich/src/README.md, ingest/src/README.md
=> Adding Test README files for basic documentation

helm-charts/health-patterns/values.yaml
=> update deid version to latest

ingest/src/test/java/tests/Ingestion_Flow.java, ingest/src/test/resources/configs/FHIR-CQL-Gender-Eval-Library.json, ingest/src/test/resources/scenarios/ingest_FHIR_BLK_CQL_$EVAL.json
=> Add FHIR-CQL $evaluate endpoint tests

.github/workflows/README.md
=> Add more detail on ibm.yaml action

helm-charts/health-patterns/Chart.yaml
=> Update HP to use LFH HA

helm-charts/health-patterns/Chart.yaml
Signed-off-by: Nick Lawrence <ntl@us.ibm.com>
=> update nlp-insights to point at linux for health

helm-charts/health-patterns/values.yaml
=> change nifi setup to quay

.github/workflows/scripts/health-patterns-build-action-yml-save.txt
=> temp disable build github action

test-umbrella/tests/tests/toolchain-envsetup.sh
Change to use USER_GIT_REPO value when doing git clone operation
=> Change to use USER_GIT_REPO

helm-charts/health-patterns/Chart.yaml
=> Update chart yaml for LfH charts

helm-charts/health-patterns/Chart.yaml, helm-charts/health-patterns/templates/NOTES.txt, helm-charts/health-patterns/values.yaml, ingest/README.md
=> add patient browser to deployment

helm-charts/health-patterns/Chart.yaml
=> change pb chart location

.github/workflows/ibm.yaml, test-umbrella/tests/tests/testCleanUp.sh
Delete PVCs after the deployment is deleted
=> Rdg delete pvcs

helm-charts/health-patterns/Chart.yaml
=> Update fhir chart to 0.6.4

helm-charts/health-patterns/Chart.yaml
=> Update nlp to 0.1.6

enrich/src/test/resources/scenarios/enrich_NLP_Insights_Config_Use.json
=> Add 10 second delay between test iterations

enrich/src/test/resources/scenarios/enrich_NLP_Insights_Override_Use.json, test-umbrella/tests/tests/run-fvttests.sh, test-umbrella/tests/tests/run-ivttests.sh, test-umbrella/tests/tests/run-smoketests.sh
Add delay between more nlp-insights tests and add fhir url to patient-browser config
=> Add delay between more nlp-insights tests and add fhir url to PB

ingest/pom.xml, ingest/src/test/java/ui/pageobjects/PageClass.java, ingest/src/test/java/ui/pageobjects/PatientDetails.java, ingest/src/test/java/ui/pageobjects/PatientList.java, ingest/src/test/java/ui/tests/PatientListPageTests.java, ingest/src/test/java/ui/tests/TestClass.java, patientData/loadscripts/loadPatientsFromDirectory.sh
Contains the Sort By and Page Scrolling Tests
Contains the patient loading script for ingesting patients with AddNLPInsights=true
=> Initial delivery of patient-browser tests

.github/workflows/ibm.yaml
=> Fix an unnoticed syntax error in the deployment uninstall step

enrich/src/test/java/tests/Enrich_Flow.java, ingest/src/test/java/tests/Ingestion_Flow.java, ingest/src/test/java/tests/Ingestion_Initialize.java, ingest/src/test/java/tests/ManualCleanUp.java, ingest/src/test/java/ui/pageobjects/PageClass.java, ingest/src/test/java/ui/pageobjects/PatientDetails.java, ingest/src/test/java/ui/pageobjects/PatientList.java, ingest/src/test/java/ui/tests/PatientListPageTests.java, ingest/src/test/java/ui/tests/TestClass.java
=> Add correct source file headers for open source projects

data-access/README.md, data-access/docker-compose.yaml, data-access/pom.xml
=> upgrade data-access compose env from ibm-fhir-server 4.10.2 to 4.11.0

ingest/src/test/java/ui/pageobjects/PatientList.java, ingest/src/test/java/ui/tests/PatientListPageTests.java
=> Initial Delivery of Demographic Tabs tests

helm-charts/health-patterns/Chart.yaml
=> Update HP to use alvearie helm 0.7.0

test-umbrella/tests/tests/run-ivttests.sh
=> Adding ASCVD tests back into IVT

enrich/src/README.md, ingest/src/README.md, ingest/src/test/java/ui/README.md, test-umbrella/tests/tests/README.md
=> Updated README files for testing

enrich/src/README.md, enrich/src/test/java/utilities/README.md, ingest/src/README.md, ingest/src/test/java/ui/README.md, ingest/src/test/java/ui/pageobjects/PatientDetails.java, ingest/src/test/java/utilities/README.md, patientData/loadscripts/patientLoadForUITest.sh
=> Documentation updates
